# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'AzureAgent'

steps:
- checkout: self

- script: mvn clean package
  workingDirectory: amazon.app
  displayName: 'Build and Package Project'

- script: |
    echo "Simulating deployment..."
    mkdir deployed
    copy target\*.jar deployed\
    echo "Deployment successful!"
  workingDirectory: amazon.app
  displayName: 'Simulate Deployment'

- script: dir deployed
  workingDirectory: amazon.app
  displayName: 'Check deployed folder'

- script: |
    echo "Running the JAR file..."
    for %%f in (deployed\*.jar) do java -jar %%f
  workingDirectory: amazon.app
  displayName: 'Run Application'
